// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://reotypssskgaedqjwcbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlb3R5cHNzc2tnYWVkcWp3Y2J1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNzcyNDIsImV4cCI6MjA2MzY1MzI0Mn0.3RWNFD4kKjiC_m2bBHpxwoBKN_xw2Y6AbeosFuXM8Iw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);